/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import {
  Cliente,
  Endereco,
  Produto,
} from './interfaces';
import {
  CartProvider,
} from './global/ServerProvider';


export namespace Components {

  interface AppBuy {}
  interface AppBuyAttributes extends StencilHTMLAttributes {}

  interface AppCadastroCustomer {
    'email': string;
    'endereco': Endereco;
    'name': string;
    'old': Cliente;
    'open': boolean;
    'pass': string;
    'placeholders': any;
    'rule': string;
    'user': string;
  }
  interface AppCadastroCustomerAttributes extends StencilHTMLAttributes {
    'email'?: string;
    'endereco'?: Endereco;
    'name'?: string;
    'old'?: Cliente;
    'onCreate'?: (event: CustomEvent<{ new: Cliente, old: Cliente }>) => void;
    'open'?: boolean;
    'pass'?: string;
    'placeholders'?: any;
    'rule'?: string;
    'user'?: string;
  }

  interface AppCadastroItem {
    'desc': string;
    'name': string;
    'old': Produto;
    'open': boolean;
    'price': number;
  }
  interface AppCadastroItemAttributes extends StencilHTMLAttributes {
    'desc'?: string;
    'name'?: string;
    'old'?: Produto;
    'onCreate'?: (event: CustomEvent<{ new: Produto, old: Produto }>) => void;
    'open'?: boolean;
    'price'?: number;
  }

  interface AppCustomer {}
  interface AppCustomerAttributes extends StencilHTMLAttributes {}

  interface AppFab {}
  interface AppFabAttributes extends StencilHTMLAttributes {
    'onOpenModal'?: (event: CustomEvent) => void;
  }

  interface AppHeader {
    'clienteProvider': any;
    'isCart': boolean;
    'isHome': boolean;
    'name': string;
  }
  interface AppHeaderAttributes extends StencilHTMLAttributes {
    'clienteProvider'?: any;
    'isCart'?: boolean;
    'isHome'?: boolean;
    'name'?: string;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppItem {}
  interface AppItemAttributes extends StencilHTMLAttributes {}

  interface AppLogin {}
  interface AppLoginAttributes extends StencilHTMLAttributes {}

  interface AppOpenCartModal {
    'cartProvider': CartProvider;
    'open': boolean;
    'update': number;
  }
  interface AppOpenCartModalAttributes extends StencilHTMLAttributes {
    'cartProvider'?: CartProvider;
    'onClose'?: (event: CustomEvent) => void;
    'open'?: boolean;
    'update'?: number;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppBuy': Components.AppBuy;
    'AppCadastroCustomer': Components.AppCadastroCustomer;
    'AppCadastroItem': Components.AppCadastroItem;
    'AppCustomer': Components.AppCustomer;
    'AppFab': Components.AppFab;
    'AppHeader': Components.AppHeader;
    'AppHome': Components.AppHome;
    'AppItem': Components.AppItem;
    'AppLogin': Components.AppLogin;
    'AppOpenCartModal': Components.AppOpenCartModal;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-buy': Components.AppBuyAttributes;
    'app-cadastro-customer': Components.AppCadastroCustomerAttributes;
    'app-cadastro-item': Components.AppCadastroItemAttributes;
    'app-customer': Components.AppCustomerAttributes;
    'app-fab': Components.AppFabAttributes;
    'app-header': Components.AppHeaderAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-item': Components.AppItemAttributes;
    'app-Login': Components.AppLoginAttributes;
    'app-open-cart-modal': Components.AppOpenCartModalAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppBuyElement extends Components.AppBuy, HTMLStencilElement {}
  var HTMLAppBuyElement: {
    prototype: HTMLAppBuyElement;
    new (): HTMLAppBuyElement;
  };

  interface HTMLAppCadastroCustomerElement extends Components.AppCadastroCustomer, HTMLStencilElement {}
  var HTMLAppCadastroCustomerElement: {
    prototype: HTMLAppCadastroCustomerElement;
    new (): HTMLAppCadastroCustomerElement;
  };

  interface HTMLAppCadastroItemElement extends Components.AppCadastroItem, HTMLStencilElement {}
  var HTMLAppCadastroItemElement: {
    prototype: HTMLAppCadastroItemElement;
    new (): HTMLAppCadastroItemElement;
  };

  interface HTMLAppCustomerElement extends Components.AppCustomer, HTMLStencilElement {}
  var HTMLAppCustomerElement: {
    prototype: HTMLAppCustomerElement;
    new (): HTMLAppCustomerElement;
  };

  interface HTMLAppFabElement extends Components.AppFab, HTMLStencilElement {}
  var HTMLAppFabElement: {
    prototype: HTMLAppFabElement;
    new (): HTMLAppFabElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppItemElement extends Components.AppItem, HTMLStencilElement {}
  var HTMLAppItemElement: {
    prototype: HTMLAppItemElement;
    new (): HTMLAppItemElement;
  };

  interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {}
  var HTMLAppLoginElement: {
    prototype: HTMLAppLoginElement;
    new (): HTMLAppLoginElement;
  };

  interface HTMLAppOpenCartModalElement extends Components.AppOpenCartModal, HTMLStencilElement {}
  var HTMLAppOpenCartModalElement: {
    prototype: HTMLAppOpenCartModalElement;
    new (): HTMLAppOpenCartModalElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-buy': HTMLAppBuyElement
    'app-cadastro-customer': HTMLAppCadastroCustomerElement
    'app-cadastro-item': HTMLAppCadastroItemElement
    'app-customer': HTMLAppCustomerElement
    'app-fab': HTMLAppFabElement
    'app-header': HTMLAppHeaderElement
    'app-home': HTMLAppHomeElement
    'app-item': HTMLAppItemElement
    'app-Login': HTMLAppLoginElement
    'app-open-cart-modal': HTMLAppOpenCartModalElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-buy': HTMLAppBuyElement;
    'app-cadastro-customer': HTMLAppCadastroCustomerElement;
    'app-cadastro-item': HTMLAppCadastroItemElement;
    'app-customer': HTMLAppCustomerElement;
    'app-fab': HTMLAppFabElement;
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-item': HTMLAppItemElement;
    'app-Login': HTMLAppLoginElement;
    'app-open-cart-modal': HTMLAppOpenCartModalElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
